### ISSUE TITLE
Replace traditional pointers with smart pointers, where possible

### ISSUE THREAD

**Issue by ghost** [CristianoNarducci/Eyeglass#13]
The program was designed with old C practices in mind. C++ has proven that using pointers is useful, but heavily error prone, thus the language engineers added ways of leveraging the pointer raw power while making it more memory safe: smart pointers.

We should use smart pointers instead of normal pointers whenever possible. If we manage, from the beginning.

Tests are to be conducted to see if wxWidget has to complain about smart pointers or not.   
It should not, as they provide smart pointer classes themselves, but who knows?

**Comment by CristianoNarducci** [comment]
pointer replaced
